kind: pipeline
name: broker-gateway

steps:
  - name: test
    image: openjdk:8-jdk-alpine
    volumes:
      - name: maven-cache
        path: /root/.m2
    commands:
      - chmod +x ./mvnw  && ./mvnw clean package -Dspring.profiles.active=product
    when:
      branch:
        - master
        - master-*
        - dev
        - fix-*



  - name: docker
    image: plugins/docker
    settings:
      username: macoredroid
      password:
        from_secret: macoredroid
      repo: macoredroid/broker-gateway
      tags:
        - v1.0.2
    when:
      branch:
        - master-*

volumes:
  - name: maven-cache
    host:
      path: /maven-cache

