apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-gateway
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: broker-gateway
    spec:
      containers:
      - name: broker-gateway
        image: registry.cn-hangzhou.aliyuncs.com/macoredroid/broker-gateway:v1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

